version: "3"
services:
  app:
    image: app:latest
    container_name: scan-api
    restart: always
    build: .
    ports:
      - "0:3000"
    logging:
      driver: awslogs
      options:
        awslogs-group: /aws/ecs/av-scanner-service
        awslogs-region: us-east-1
        awslogs-stream-prefix: clam_api
    env_file:
      - api.env
